CREATE TABLE Shipments (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    CustomerId INT NOT NULL,
    ShipmentId VARCHAR(128) NOT NULL,
    OrderId VARCHAR(128) NOT NULL,
    TrackingNumber VARCHAR(255) DEFAULT '',
    Carrier VARCHAR(100) DEFAULT '',
    Service VARCHAR(100) DEFAULT '',
    ShippedDate DATETIME NOT NULL,
    CreatedDateUtc DATETIME NOT NULL,
    UpdatedDateUtc DATETIME NOT NULL,
    Status VARCHAR(50) DEFAULT '',
    ShippingCost DECIMAL(18,2) DEFAULT 0.00,
    RecipientName VARCHAR(255) DEFAULT '',
    RecipientAddress VARCHAR(500) DEFAULT '',
    RecipientCity VARCHAR(100) DEFAULT '',
    RecipientState VARCHAR(50) DEFAULT '',
    RecipientZip VARCHAR(20) DEFAULT '',
    RecipientCountry VARCHAR(100) DEFAULT '',
    FOREIGN KEY (CustomerId) REFERENCES Customers(Id) ON DELETE CASCADE,
    UNIQUE KEY UK_Shipments_CustomerShipment (CustomerId, ShipmentId),
    INDEX IX_Shipments_OrderId (OrderId),
    INDEX IX_Shipments_ShippedDate (ShippedDate)
);